root = "."

tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/api ./cmd/server"
bin = "./tmp/api"
include_ext = ["go", "tpl", "tmpl", "html", "env"]
include = [".env", ".env.local"]
include_regex = [".*\\.env(\\.local)?$"]
exclude_dir = ["vendor", "tmp", "testdata", "node_modules", ".git"]
exclude_regex = ["_test\\.go$"]
delay = 1000
stop_on_error = true
send_interrupt = true
kill_signal = "kill"

[log]
time = true

[env]
APP_ENV = "development"
